fixtures:
  forge_modules:
    stdlib:
      repo: puppetlabs/stdlib
      ref: 8.6.0
  repositories:
    command_args: "git://github.com/pcfens/puppet-command_args.git"
  symlinks:
    rhn_register: "#{source_dir}"
